### ISSUE TITLE
Product Description

### ISSUE THREAD

**Issue by Amentegegne04** [irm1005-itec1005-fall-2023/assignment-05-binarybounty#1]
# Product Description

## High Level Overview

We are going to build a landing page for grocery store to promote the products they are offering and deals they currently have.

## Problem Statement

We would like to find new business because our store is new in Ottawa.

## Moments of Charm

Photos, videos, design that responds to users with motion.

## Product Sketches

![sketch of project](https://github.com/irm1005-itec1005-fall-2023/assignment-05-binarybounty/assets/144935533/c1a37ea6-2ac5-48ce-921f-ddc1228c8390)

**Comment by neilmispelaar** [comment]
Hey @irm1005-itec1005-fall-2023/binarybounty 

Check HTML comments - we can't read your product description

<img width="755" alt="Screenshot 2023-11-28 at 10 30 14 AM" src="https://github.com/irm1005-itec1005-fall-2023/assignment-05-binarybounty/assets/9325038/cdbdee83-076d-42eb-be4a-98eb25f15f3b">

**Comment by webba111** [comment]
Hi Neil!

I have just updated the project description and hopefully you can read it.

**Comment by neilmispelaar** [comment]
Hi @irm1005-itec1005-fall-2023/binarybounty 

Great work with your Product Description. 

I love the idea of a Grocery Store home page. 

**One word of advice:** please add more content to your page. Looking at your sketch - it is looking a bit thin - make sure that you add lots of relevant content so that you get a solid mark. 

Take a look at these to see just how much content they have and what sections you can "borrow".

https://www.farmboy.ca/
https://www.loblaws.ca/
https://www.metro.ca/en?utm_content=12468278_1333253161_58836805412&utm_campaign=1333253161&utm_source=google&utm_medium=cpc&gad_source=1&gclid=EAIaIQobChMI4Jm69pvsggMVme_ICh3uBgWlEAAYASAAEgLzLvD_BwE&gclsrc=aw.ds

**Comment by webba111** [comment]
Definitely, we will adjust our strategy specifically to add more features.
